-- MySQL Script generated by MySQL Workbench
-- Tue Sep  1 11:29:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema examlibrarydb
-- -----------------------------------------------------
-- Stores data related to online exams

-- -----------------------------------------------------
-- Schema examlibrarydb
--
-- Stores data related to online exams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `examlibrarydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`user_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_1` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

USE `examlibrarydb` ;

-- -----------------------------------------------------
-- Table `examlibrarydb`.`CustomerRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examlibrarydb`.`CustomerRole` (
  `Role ID` INT NOT NULL,
  `RoleName` VARCHAR(10) NULL,
  PRIMARY KEY (`Role ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examlibrarydb`.`CustomerAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examlibrarydb`.`CustomerAccount` (
  `CustId` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `EmailID` VARCHAR(45) NOT NULL,
  `PasswordHash` BLOB NULL,
  `PhoneNumber` INT NULL,
  `Country` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `PasswordSalt` BLOB NULL,
  `RoleId` INT NULL,
  INDEX `RoleId_idx` (`RoleId` ASC) VISIBLE,
  PRIMARY KEY (`EmailID`),
  UNIQUE INDEX `CustId_UNIQUE` (`CustId` ASC) VISIBLE,
  CONSTRAINT `RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `examlibrarydb`.`CustomerRole` (`Role ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examlibrarydb`.`SimTest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examlibrarydb`.`SimTest` (
  `TestID` INT NOT NULL AUTO_INCREMENT,
  `TestName` VARCHAR(45) NULL,
  `Duration` FLOAT NULL,
  `Percentage` FLOAT NULL,
  `NoOfQuestions` INT NULL,
  `EmailId` VARCHAR(45) NULL,
  PRIMARY KEY (`TestID`),
  INDEX `custid_idx` (`EmailId` ASC) VISIBLE,
  CONSTRAINT `custid`
    FOREIGN KEY (`EmailId`)
    REFERENCES `examlibrarydb`.`CustomerAccount` (`EmailID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examlibrarydb`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examlibrarydb`.`Questions` (
  `QuestionID` INT NOT NULL AUTO_INCREMENT,
  `Question` VARCHAR(100) NULL,
  `CorrectAnswer` VARCHAR(100) NULL,
  `TestID` INT NULL,
  PRIMARY KEY (`QuestionID`),
  INDEX `TestId_idx` (`TestID` ASC) VISIBLE,
  CONSTRAINT `TestId`
    FOREIGN KEY (`TestID`)
    REFERENCES `examlibrarydb`.`SimTest` (`TestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examlibrarydb`.`ChoiceTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examlibrarydb`.`ChoiceTable` (
  `ChoiceID` INT NOT NULL AUTO_INCREMENT,
  `QuestionID` INT NULL,
  `ChoiceOne` VARCHAR(100) NULL,
  `ChoiceTwo` VARCHAR(100) NULL,
  `ChoiceThree` VARCHAR(100) NULL,
  `ChoiceFour` VARCHAR(100) NULL,
  PRIMARY KEY (`ChoiceID`),
  INDEX `QuestionID_idx` (`QuestionID` ASC) VISIBLE,
  CONSTRAINT `QuestionID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `examlibrarydb`.`Questions` (`QuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examlibrarydb`.`AssignedTestTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examlibrarydb`.`AssignedTestTable` (
  `EmailID` VARCHAR(45) NULL,
  `TestID` INT NULL,
  `CorrectAnswers` INT NULL,
  `WrongAnswers` INT NULL,
  `Percentage` FLOAT NULL,
  `AssignedTestID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`AssignedTestID`),
  INDEX `CustId_idx` (`EmailID` ASC) VISIBLE,
  CONSTRAINT `EmailId`
    FOREIGN KEY (`EmailID`)
    REFERENCES `examlibrarydb`.`CustomerAccount` (`EmailID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
